### ISSUE TITLE
Symbolic links

### ISSUE THREAD

**Issue by nsberrow** [Wodby/docker4wordpress#10]
How do you add a symbolic link to a repo inside the container to dev locally?

**Comment by csandanov** [comment]
There's no way to add a symbolic link outside of a container. Are you sure you need it? Are volumes not enough for some reason?

**Comment by nsberrow** [comment]
It's so I can read my project in my IDE locally.

**Comment by csandanov** [comment]
That's exactly why we use volumes, to mount directories from your host machine to the container. Please follow the instructions and put the compose file to the directory with your project.

**Comment by nsberrow** [comment]
Thanks, got it working.
