### ISSUE TITLE
localhost:8000 -> Nginx 403 Forbidden

### ISSUE THREAD

**Issue by gfelot** [wodby/docker4wordpress#12]
I have an 403 when I try to it Wordpress.

I did not change something in the compose file except activated redis and memcached.

PMA and MailHog work fine.

**Comment by csandanov** [comment]
Most likely you have a problem with permission inside of your container.

**Comment by csandanov** [comment]
@gfelot I'm closing this issue, if you still have the problem please provide more details on your docker version, OS and steps to reproduce.
