### ISSUE TITLE
PHP_XDEBUG_ENABLED activates empty file

### ISSUE THREAD

**Issue by ed4becky** [wodby/docker4wordpress#14]
I am not clear on what PHP_XDEBUG_ENABLED=1 is supposed to do.  I activated, and I see in phpinfo it has activated an empty xdebug.ini file.

The xdebug module does not seem to get loaded (per php -m)

**Comment by ed4becky** [comment]
I tried this so I could customize the ini
      - ./docker-runtime/php:/usr/local/etc/php
      - ./docker-runtime/php/conf.d:/usr/local/etc/php/conf.d

however the xdebug.ini file gets overwritten (with an empty file) every time its brought up

**Comment by csandanov** [comment]
We've release a new revamped 2.0 version, see the list of env vars available for customization https://github.com/wodby/php

**Comment by csandanov** [comment]
Article about xdebug has been added http://docs.docker4wordpress.org/en/latest/containers/php/#xdebug
