### ISSUE TITLE
Error after install: 403 Forbidden

### ISSUE THREAD

**Issue by zreese** [wodby/docker4wordpress#16]
Following the Getting Started guide letter for letter, visiting http://wp.docker.localhost:8000/ displays 403 Forbidden. Tried a second time, same result.

I'm on macOS running Docker for Mac Version 17.03.1-ce-mac5 (16048).

**Comment by csandanov** [comment]
I've just tried and couldn't reproduce. I rebuilt php image just in case with fresh wodby/php, so you can try pulling image `wodby/wordpress-php:7.0-2.0.0` again and see if it helps.

If not, please show the logs via `docker-compose logs php|nginx`.

**Comment by mckernanin** [comment]
I just had the same thing happen, in my case my project directory didn't have anything other than my docker-compose.yml. I created an index.php file and it showed up properly, so I'm guessing the issue is not having a WP install in the folder.

**Comment by csandanov** [comment]
With new docker4wordpress 2.1.0 you can now deploy vanilla WordPress without mounting your own codebase: http://docs.docker4wordpress.org/en/latest/#1-run-vanilla-wordpress-from-image-default
