### ISSUE TITLE
Pending request in any browser except Chrome

### ISSUE THREAD

**Issue by ervasive** [wodby/docker4wordpress#19]
So I have a weird problem accessing docker4wordpress setup with any browser (or curl) except Google Chrome. I'm not sure if it's reproducible outside of my machine, but here it is.

Steps to reproduce:
```
git clone https://github.com/wodby/docker4wordpress.git
cd docker4wordpress
docker-compose up
```

After all containers are provisioned and ready, I can go ahead and start WordPress installation with Google Chrome with no problem whatsoever, but if I try to access the same url (wp.docker.locahost:8000) with Firefox, Safari curl I have connection timeout.

Now if I change NGINX container `host` label for Traefik to:
```
'traefik.frontend.rule=Host:localhost'
```
then I can access the URL (http://localhost:8000) from everywhere.

It seems that the problem is that Traefik does not proxy request properly (actually I have no idea).

Does anyone have this problem? Any way to solve it?

Thanks

**Comment by csandanov** [comment]
Yes, this issue have been reported more than once by [folks using docker4drupal](https://github.com/wodby/docker4drupal/issues/117#issuecomment-298658518), also on [docker forums](https://forums.docker.com/t/localhost-dns-doesnt-resolve-in-browsers-other-than-chrome/16300/2). Perhaps localhost subdomains is a very exotic solution despite being supported by chrome, the quick solution is to add the host to /etc/hosts.

**Comment by ervasive** [comment]
Oh, interesting. Thanks for pointing this out.

**Comment by csandanov** [comment]
Added a warning to docs http://docs.docker4wordpress.org/en/latest/domains/
