### ISSUE TITLE
403 error at localhost:8000 after installation

### ISSUE THREAD

**Issue by wpjim** [Wodby/docker4wordpress#2]
- Docker for Windows version 1.12.0-stable (build: 5968)

After I `docker-compose build`, `docker-compose create`, and `docker-compose start`, Nginx is logging that directory index is forbidden. (note, I have to do this instead of `docker-compose up` due to a[ different issue](https://github.com/docker/compose/issues/3851) currently affecting docker for windows)

When I connect to the wpdocker4wp_php shell I don't see any files in /var/www/html, only the directory 'docker-runtime', even though kitematic is showing that I the host directory is properly shared.

In addition, "docker-runtime" is not created in the host directory, which I thought should happen based on the install instructions.

**Comment by hrdcdr** [comment]
Please check access to host volumes in your docker for win installation (see options of docker tree icon). Likely it was not configured.
Also please pay attention to another docker for win issue docker/for-win#39. The workaround for this problem described in Wodby/docker4drupal#29.

**Comment by wpjim** [comment]
Thanks, I did have my C drive shared in settings. It turned out to be an issue with Windows Firewall. The DockerNAT network created during Docker for Windows Installation was identified by Windows as and Unidentified Network. Setting Unidentified Networks to Private in Control Panel -> Local Security Policy ->Network List Manager Policies fixed my problem.
