### ISSUE TITLE
Issue with WordPress trademark?

### ISSUE THREAD

**Issue by HeikoMamerow** [wodby/docker4wordpress#20]
Hi Chingis,
did you know, the WordPress Foundation Trademark Usage Policy has a strikt regulation for the use of "WordPress" in domain names: 

> "Please do not use WordPress or WordCamp as part of a domain name." 

Source: http://wordpressfoundation.org/trademark-policy/

I think, it is better if you rename your domain in: docker4wp.org. This is the normal way to name WordPress in domains.

Hope this was helpful :-)

**Comment by csandanov** [comment]
Ohh.. wasn't aware of that, thanks for the heads-up

**Comment by csandanov** [comment]
We dropped docker4wordpress.org, now using only http://docker4wordpress.readthedocs.io/en/latest/ and https://github.com/wodby/docker4wordpress

**Comment by HeikoMamerow** [comment]
Great! :+1: 

...and woooow, you are fast! :1st_place_medal:
