### ISSUE TITLE
database user issue

### ISSUE THREAD

**Issue by pjv** [wodby/docker4wordpress#21]
I just spun up a test docker4wordpress dev instance on my mac and when I got to the wordpress setup step, I was unable to proceed with the documented database user ("wordpress"). I had to use "root" instead of "wordpress". The default "wordpress" password worked correctly.

Prior to bringing up the services, I edited the `docker-compose.yml` to run nginx instead of apache (commented the apache service section, uncommented the nginx service section).

I didn't change anything in the mariadb service section which does set `MYSQL_USER: wordpress` under `environment`.

I'm just wondering where the wp db user should be getting set up and how the specified environment variable is not being used.

**Comment by csandanov** [comment]
Did you specify `mariadb` as a db host? I've just run it from scratch on macOS (nginx as http server) and it worked. Please past your compose file here.

**Comment by pjv** [comment]
I did specify `mariadb` as db host.

```
➤ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/wordpress:4-7.1-2.2.0
#    image: wodby/wordpress:4-7.0-2.2.0
#    image: wodby/wordpress-php:7.0-2.2.0
#    image: wodby/wordpress-php:7.1-2.2.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - codebase:/var/www/html
# Options for macOS users (http://docs.docker4wordpress.org/en/latest/macos)
      # - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync

  nginx:
    image: wodby/wordpress-nginx:4-1.13-2.2.0
#    image: wodby/wordpress-nginx:4-1.12-2.2.0
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - codebase:/var/www/html
# Options for macOS users (http://docs.docker4wordpress.org/en/latest/macos)
      # - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    depends_on:
      - php
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:wp.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.wp.docker.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.wp.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:
## Docker-sync for macOS users
#  docker-sync:
#    external: true


```

**Comment by csandanov** [comment]
I've just tried with your compose file and successfully installed WordPress. Entered `wordpress` as user, password and db name, `mariadb` as host. And I have the same docker version. Could you please make a screenshot of the step where it fails, maybe I just don't understand what's the issue.

**Comment by pjv** [comment]
![2017-07-06 at 8 15 am](https://user-images.githubusercontent.com/327716/27912753-8f00a020-6223-11e7-9ab3-ad0008a4aa5c.png)

![2017-07-06 at 8 15 am](https://user-images.githubusercontent.com/327716/27912785-a6d04714-6223-11e7-8099-0f45fac8814a.png)

![2017-07-06 at 8 15 am](https://user-images.githubusercontent.com/327716/27912800-b4a2fb70-6223-11e7-8847-ae4bf7883e25.png)

![2017-07-06 at 8 16 am](https://user-images.githubusercontent.com/327716/27912817-c031a68a-6223-11e7-8db4-f8994e69afba.png)


in case any of this makes a difference:

![2017-07-06 at 8 21 am](https://user-images.githubusercontent.com/327716/27912940-22a76e80-6224-11e7-822b-4ae21557343e.png)

**Comment by csandanov** [comment]
Password must be wordpress

**Comment by pjv** [comment]
Headslap.

So sorry for the waste of time.
