### ISSUE TITLE
Cannot start service traefik: driver failed programming external connectivity

### ISSUE THREAD

**Issue by slaFFik** [wodby/docker4wordpress#25]
### Codebase
Built-in vanilla WordPress or mounted codebase
  
### Host OS 

Windows 10 Pro with Hyper-V

### Docker info output
```
ERROR: for traefik  Cannot start service traefik: driver failed programming external connectivity on endpoint nginx_traefik_1 (56761d779bd3d63841b709c8a8fa4aa2a763aa0e2244204c1dd6aeb92d6b1523): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8000:tcp:172.18.0.3:80: input/output error
```

### Docker compose file

Same as in the repo, no changes.

**Comment by csandanov** [comment]
Most likely the default port `8000` isn't free on your host machine, also see https://github.com/docker/compose/issues/3277

**Comment by slaFFik** [comment]
I remember, that I turned off local server to free the port, but that didn't help. It was a midnight for me though, so I might messed up with something.
Anyway, I've changed a port to 8888 - and all is good. I'm ok with URL like `http://wp.docker.localhost:8888/`. It's for debugging purpose anyway.

Thank you!

**Comment by Streamweaver** [comment]
In case this helps.  I had the same error.  The problem was that one of the services I had didn't stop one of the containers correctly and it was still sitting in my container list as exited.  So I removed the exited instance and restarted, all was fine.
