### ISSUE TITLE
Newbie Questions

### ISSUE THREAD

**Issue by danielbarenkamp** [wodby/docker4wordpress#27]
Hello,

I am a bit new to docker so excuse me my may stupid questions :) But I hope you can answer me some. I have successfully installed the vanilla wp docker on my Debian 9.3.

## How do I edit the Config files?

For example where can I edit the php.ini / nginx settings? When I do a find I oly get strange folder points: 
```
find / -name "php.ini"
/var/lib/docker/overlay2/f6f34790839e5d2010cc72eeaa8aa10303e202be68fec6b977653a4ab8a0bb8b/diff/etc/supervisor.d/php.ini
/var/lib/docker/overlay2/f6f34790839e5d2010cc72eeaa8aa10303e202be68fec6b977653a4ab8a0bb8b/diff/etc/php.ini
/var/lib/docker/overlay2/440f1f536d60460793085b144aa59da814df6e3eb5708d44b9c16fe1b0168fda/merged/etc/supervisor.d/php.ini
/var/lib/docker/overlay2/440f1f536d60460793085b144aa59da814df6e3eb5708d44b9c16fe1b0168fda/merged/etc/php.ini
```

## How do I best create / develop own plugins / themes?
I found out, that the files are located somewhere in "/var/lib/docker/volumes/XXX_codebase/_data/". Do I need to create a FTP service and edit files directly there? 

## How do I update the docker?
Let's say a new PHP version comes out, how do I best update my docker? Simply replace the php line in my docker-compose.yml and restart docker? Do any files get lost (e.g. modified php.ini)?

## How do I backup docker wordpress?
How do I best backup my wordpress docker? Backup files and database?

## How can I secure the access?
When I go to pma.XXX.com everybody from public can go into my phpmyadmin. How can I prevent this?

## How can I create a staging version?
How do I create a staging version of this docker? Something where I can play around with code and if okay, push to the production docker?

Sorry for my newbie questions - hope you can help me!

**Comment by csandanov** [comment]
> How do I edit the Config files?

via environment variables, you can see them at https://github.com/wodby/php#environment-variables and https://github.com/wodby/nginx#environment-variables

> How do I best create / develop own plugins / themes?

If we're talking about the local environment you mount your own codebase to php/nginx containers as [described in docs](https://wodby.com/stacks/wordpress/docs/local/quick-start/#option-2-mount-my-wordpress-codebase). I recommend using composer template to install wp core and contrib plugins/themes for https://github.com/wodby/wordpress-composer

> How do I update the docker?

When new PHP comes out and we release a new version of d4w with a new set of images, you just update your images tags

> How do I backup docker wordpress?

The same way you do it without docker

> How can I secure the access?
> How can I create a staging version?

There are plenty of ways to do that but they require a certain level of knowledge, if you're looking for an automated ready-to-run solution I recommend taking a look at https://wodby.com
