### ISSUE TITLE
Edit apache httpd.conf

### ISSUE THREAD

**Issue by cesco69** [wodby/docker4wordpress#29]
### Codebase
Built-in vanilla WordPress
  
### Host OS 
Ubuntu 16.04

I'm trying docker4wordpress with apache. 
How can I edit httpd.conf?

For example I need to add modules or modify settigs not included in the provided Environment Variables.
When I try to edit it with a bash inside apache container I was prompted to insert wodby password, but I don't find it anywere.

Thanks

**Comment by csandanov** [comment]
We've added `APACHE_INCLUDE_CONF` for this in 3.0.2 tag:

* Update apache image tag to `-3.0.2`
* Copy `/usr/local/apache2/conf/conf.d/vhost.conf` to your codebase and modify to your needs
* Set environment variable `APACHE_INCLUDE_CONF=/var/www/html/vhost.conf` 
* Your `vhost.conf` will be included to the main `httpd.conf` (don't mind the filename, you can use it not only for virtual host configuration)

**Comment by csandanov** [comment]
Oh, I see you're using vanilla WP, in this case you can modify `/usr/local/apache2/conf/httpd.conf` directly in the apache container and run `sudo httpd -k restart`

**Comment by cesco69** [comment]
@csandanov the same feature is also useful for php.ini (PHP) file and my.ini (MySQL/MariaDB).

Thanks a lot!

**Comment by cesco69** [comment]
I should enable some modules for example: 

    LoadModule remoteip_module modules/mod_remoteip.so

These instruction usually are at the beginning of httpd.conf, how can I enable modules at the beginning og httpd.conf?

**Comment by csandanov** [comment]
You can load modules in your config file included in `httpd.conf`, they not necessarily should be in the beginning. AFAIK there's no way to disable module in `httpd.conf`.

Can you share with me what are you trying to achieve, maybe it can be done easier with nginx (which is more preferred).
