### ISSUE TITLE
Use unix line endings

### ISSUE THREAD

**Issue by brandonkal** [wodby/docker4wordpress#36]
Many files such as wp-config.php seem to have Windows line endings. This clutters the file when viewed with ^M displayed on every line when using vi/vim. Please consider switching to standard unix line endings only. Thank you.

**Comment by csandanov** [comment]
That's the official WP sources downloaded via wp cli, we don't change it

**Comment by brandonkal** [comment]
That is very interesting. When I download the official wordpress image and look at `wp-config-sample.php` for instance, the line endings are standard unix line endings. I know the the docker-library/wordpress Dockerfile downloads the zip from wordpress.org and extracts it on build so it is a little strange that there is a difference between methods.

Regardless, it is not a very big deal since the file is coming from upstream.
