### ISSUE TITLE
Feature request: WordPress as a container

### ISSUE THREAD

**Issue by otravers** [wodby/docker4wordpress#4]
It would be nice to have the whole stack as containers. I'm guessing you'd have to integrate the WP fpm version since their default/latest tag includes Apache:
https://github.com/docker-library/wordpress/tree/81d061a68456cc14fcebb88a17b61d600eac30e9/fpm

**Comment by otravers** [comment]
Sorry if I poorly phrased my request. No, I do not mean joining all the containers into one, that would defeat Docker's purpose.

I meant that it would be nice to have WordPress in its own container, which I ended up doing myself by adding the wordpress:fpm image to my docker-compose file.

**Comment by csandanov** [comment]
Ohh, I see. It's just we oriented on developers who use git and place the docker-compose file to the codebase with their custom WP project

**Comment by otravers** [comment]
Right. The idea is to set up the WordPress core in its own subdirectory and not commit it to the custom WP project's git repository. In the end there are many ways to skin that cat:

- WP in its own Docker container retrieved with Docker Compose from Docker Hub
- WP retrieved with Composer from Packagist
- WP retrieved with Git from Github

**Comment by Pushplaybang** [comment]
this would be a great benefit, and is literally the only reason i didn't start with this

**Comment by csandanov** [comment]
@otravers not sure I understand you, you don't have to commit anything to use docker4wordpress, there's no difference how you get your WP code, you just need to mount the directory with the code to the containers (nginx and php), that's all.

**Comment by otravers** [comment]
@csandanov My comment was about putting WordPress in its own directory so that it's easy to exclude it from my project Git repository. In the past I used a Git submodule for WP, now I'm using Composer using a structure similar to what Bedrock does.

**Comment by csandanov** [comment]
@otravers I think the composer is the right way to do it instead of having core inside of the container separated from your codebase. I'm closing this issue if you don't mind.
