### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by phsab** [wodby/docker4wordpress#5]
wordpress-php creates uid and gid 82 (www-data), but wordpress-nginx doesn't create uid 82, only the gid. This causes the famous 'asking for ftp credentials' when adding or deleting plugins/themes.

**Comment by PavelPrischepa** [comment]
Hi @phsab,

You should change permissions for the docroot directory.

From the host machine: `sudo chown -R 82:82 wordpress`.
Or from the PHP conatiner: `chown -R www-data:www-data /var/www/html`.

**Comment by bestimmaa** [comment]
Can confirm: ``docker-compose exec php sh`` into the container and ran ``chown -R www-data:www-data /var/www/html `` to resolve it
