### ISSUE TITLE
webgrind tag 1.5-1.13.1 osbolete

### ISSUE THREAD

**Issue by ybabel** [wodby/docker4wordpress#55]
https://github.com/wodby/docker4wordpress/blob/d1676f6d5fed1240a8964376238b1a43b8db1d61/.env#L98

tag 1.5-1.13.1 don't work any more.
On webgrind project it seem's that it's 1.6-something but I did not found what. I tried with "latest"

**Comment by csandanov** [comment]
Thank you, kinda missed that with the auto-update to 1.6, didn't know it's still maintained. Now it's set to `1-1.13.1`
