### ISSUE TITLE
cannot launch webgrind

### ISSUE THREAD

**Issue by ybabel** [wodby/docker4wordpress#56]
`ERROR: for webgrind  Cannot create container for service webgrind: failed to mkdir /var/lib/docker/volumes/docker4wordpress_files/_data/sessions: mkdir /var/lib/docker/volumes/docker4wordpress_files/_data/sessions: file exists
`
maybe it's conflicting with another container ? I did not checked. Do you want my docker-compose.yml ?

**Comment by csandanov** [comment]
It doesn't look like the error from a container output, most likely you've confused something with bind mounts (volumes). How to reproduce it?

**Comment by ybabel** [comment]
Indeed, I could not reproduce it myself this morning !

**Comment by ybabel** [comment]
So I did finally reproduced it : it took a "make prune" and then restart. But ... the second time I tried to reproduce, after make prune, everything get right. Nevermind !
