### ISSUE TITLE
Redis plugin not working

### ISSUE THREAD

**Issue by ybabel** [wodby/docker4wordpress#57]
I have the wordpress site running, portainer also, default .env (just changed the project name). I have added url & project name to /etc/hosts

![image](https://user-images.githubusercontent.com/1323282/70641689-4a667480-1c3e-11ea-8b14-41289cd87955.png)
 I think it's related to the default server configuration. 127.0.0.1:6379 is not reachable from the php container. I don't know how to correct it. Maybe in traefik ?

**Comment by csandanov** [comment]
Redis isn't running on `127.0.0.1`, it's in another container, host `redis`

**Comment by ybabel** [comment]
Yes, it worked, thank you.
I had to add in wp-config.php :
`define ('WP_REDIS_HOST', 'redis');`
Is there a way to pass that from docker-compose.yml to the container itself ? (I suppose via en environment variable and a script but maybe there is a more elegant solution - I'm new to docker-compose)
