### ISSUE TITLE
varnish connection refused

### ISSUE THREAD

**Issue by ybabel** [wodby/docker4wordpress#58]
I think it's the same kind of problem in varnish than in redis :

```
Wed Dec 11 16:53:30 UTC 2019 - Processing 127.0.0.1:6081 
Wed Dec 11 16:53:30 UTC 2019 - Error connecting to 127.0.0.1:6081 : Connection refused (111)
```

plugin used : Varnish Wordpress Version 1.7 | By AdminGeekZ

**Comment by csandanov** [comment]
Is this plugin logs? I see you're connecting `127.0.0.1`, varnish host is `varnish` by default

**Comment by ybabel** [comment]
Yes, thank you.
