### ISSUE TITLE
crond --path valid?

### ISSUE THREAD

**Issue by pjv** [wodby/docker4wordpress#67]
I don’t know if this is true for all, but as far as I can tell, the --path argument for the crond container (in docker-compose.yml) is pointing to a non-existent location.

`--path=/var/www/html/web` -- does not exist (at least in my stack)

`--path=/var/www/html` -- where the wordpress install is mounted (in my stack)

**Comment by csandanov** [comment]
It was probably copy-pasted from docker4drupal, fixed now
