### ISSUE TITLE
Question about WP_ Salt env vars.

### ISSUE THREAD

**Issue by audetcameron** [wodby/docker4wordpress#68]
Hello, I have a question on the .env SALT variables used in docker4wordpress.
I use bedrock and they use 
```

# Generate your keys here: https://roots.io/salts.html
AUTH_KEY='generateme'
SECURE_AUTH_KEY='generateme'
LOGGED_IN_KEY='generateme'
NONCE_KEY='generateme'
AUTH_SALT='generateme'
SECURE_AUTH_SALT='generateme'
LOGGED_IN_SALT='generateme'
NONCE_SALT='generateme'
```
https://github.com/roots/bedrock/blob/master/.env.example

however, your .env example has them written as
```
WP_AUTH_KEY='generateme'
WP_AUTH_SALT='generateme'
WP_SECURE_AUTH_KEY='generateme'
WP_SECURE_AUTH_SALT=generateme'
WP_LOGGED_IN_KEY='generateme'
WP_LOGGED_IN_SALT='generateme'
WP_NONCE_KEY='generateme'
WP_NONCE_SALT='generateme'
```
with the WP_ preface. I was just wondering if your salt env vars are being used and or if they needed to be included?
Thanks,

**Comment by csandanov** [comment]
Good point, these env vars although supported by vanilla WP image not passed through by default. I've changed it so they passed through in `docker-compose.override.yml` but commented in `.env`, if env vars are empty salts will be generated randomly
