### ISSUE TITLE
Nginx short-term caching

### ISSUE THREAD

**Issue by otravers** [wodby/docker4wordpress#8]
Small changes to PHP pages are not reflected instantly after a browser refresh (even a hard refresh). I suspect Nginx might be set up with sendfile = on. Is there a way to set sendfile to off right from the docker-compose file? If not, how can I edit the container's Nginx.conf?

I googled around but couldn't find answers to either questions, though I'm not an Nginx or Docker expert.

**Comment by PavelPrischepa** [comment]
I didn't face the issue like that before. It's probably related to PHP OpCache settings `opcache.revalidate_freq = 2`. Try to disable OpCache. BTW, you can override any file in containers via docker volumes.

**Comment by otravers** [comment]
You're right, especially because I'm using PHP-FPM coming with the WordPress container (i.e. not your PHP image) and it turns out their opcache was set to 60. I disabled it altogether. I'm aware of settings override which I had to use for MariaDB (per https://github.com/Wodby/docker4wordpress/issues/9) and also to increase file PHP upload limits, as per https://github.com/docker-library/wordpress/issues/10#issuecomment-241145416

I did a couple quick tests and it seems the short-term caching issue is gone. Thank you, you can close this issue.
