### ISSUE TITLE
Is should work wp cli autocompletion?

### ISSUE THREAD

**Issue by OlegApanovich** [wodby/docker4wordpress#80]
First at all thanks guys for your work. And I have a question.
Is wp cli autocompletion should work?
Cos I can see that environment already has /usr/local/include/wp-completion.bash 
And can see  that it has already been added to .bash_profile and .bashrc  as a directive 'source /usr/local/include/wp-completion.bash'
But autocompletion does not work when I for example connect to shell 'make shell' and try to execute 'wp pl' pres tab and nothing happens. Maybe I am doing it wrong?
Also when I try to execute 'source ~/.bashrc' in shell I always can see the error 'sh: /usr/local/include/wp-completion.bash: line 12: syntax error: unexpected "(" (expecting "fi")'

Please help me is the current environment support wp cli autocompletion at all? And if yes then how I can figure out it works?

**Comment by csandanov** [comment]
Thank you for reporting this, `wp-completion.bash` script wasn't executable
