### ISSUE TITLE
Allow access to Mariadb from host applications (binding?)

### ISSUE THREAD

**Issue by otravers** [Wodby/docker4wordpress#9]
What I'm trying to accomplish: I'm trying to access the Mariadb database from Windows apps such as PhpStorm or SQLyog with 10.0.75.1 as the host address and 3306 as the port.

Problem: I haven't been able to connect from them despite triple-checking credentials. I can check that the database is up and running from PHPMyAdmin or WordPress. Thus I suspect it's a binding problem, so I wanted to add bind-address=0.0.0.0 to the cnf file. Since I'd rather not mess with images/Dockerfile, I added the following to the volumes section of my db container in the docker-compose file:      

- ./client/mariadb-init/conf:/etc/mysql/conf.d

In /client/mariadb-init/conf (i.e. the directory on my Windows host) I have a config-file.cnf file with the bind settings referenced above. I restarted the container with the expectation that I'd have overridden the bind setting with my file, on top of whatever else is in the default my.cnf.

The container log shows "[Note] Server socket created on IP: '0.0.0.0'." which looked encouraging but MariaDB remains unreachable from the host.

References:
- https://mariadb.com/kb/en/mariadb/configuring-mariadb-for-remote-client-access/
- https://hub.docker.com/r/_/mariadb/

Once that's resolved I guess I may also need to grant privileges to the wordpress MySQL user but I can always do that through PhpMyAdmin.

**Comment by PavelPrischepa** [comment]
Hi @otravers,

You cannot connect to the MariaDB, because it isn't in your host machine network. I should map port 3306 to you host machine network like you map 80 to 8000 in PHP container.

```
mariadb:
...
    ports:
      - "53306:3306"
...
```

Then you could connect to the MariaDB via: `mysql --protocol=TCP -P53306 -u<USER> -p<PASSWORD> <DB NAME>`.

**Comment by otravers** [comment]
Of course! Thanks a lot, you can close this ticket.
